name: ObsidianPDFGenCI

on:
  # - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, args: "--no-manual" }
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive-latex-extra texlive-fonts-extra
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Create tex and pdf files
          path: |
            tests/test_files/*.tex
            tests/test_files/*.pdf
